// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6wmKTd2xTlg3w9er571ilxF2-GFXlaVU',
    appId: '1:514753990478:web:26f9963488b5ebda54581f',
    messagingSenderId: '514753990478',
    projectId: 'practical-test-35785',
    authDomain: 'practical-test-35785.firebaseapp.com',
    storageBucket: 'practical-test-35785.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqKxkG2zk85OqQCtm4Cbl-TdFJOKa3iFM',
    appId: '1:514753990478:android:68383913a734730754581f',
    messagingSenderId: '514753990478',
    projectId: 'practical-test-35785',
    storageBucket: 'practical-test-35785.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYUmH_54yq6pSmvaSWuFk6jaIkUgmeqOs',
    appId: '1:514753990478:ios:355d9ee291394ac954581f',
    messagingSenderId: '514753990478',
    projectId: 'practical-test-35785',
    storageBucket: 'practical-test-35785.firebasestorage.app',
    iosBundleId: 'com.example.practicalTest',
  );
}
